plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'com.telecombridge.simulator.DiameterSimulator'
}

dependencies {
    implementation project(':diameter-codec')

    implementation libs.netty.buffer
    implementation libs.netty.transport
    implementation libs.netty.codec
    implementation libs.netty.handler

    implementation libs.slf4j.api
    implementation libs.logback.classic
}
